/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as SettingsRouteRouteImport } from './routes/settings/route'
import { Route as SplashRouteImport } from './routes/splash'
import { Route as UpdateRouteImport } from './routes/update'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppAboutRouteImport } from './routes/app/about'
import { Route as AppAnimeListRouteImport } from './routes/app/anime-list'
import { Route as AppHistoryRouteImport } from './routes/app/history'
import { Route as AppNowPlayingRouteImport } from './routes/app/now-playing'
import { Route as AppSearchRouteImport } from './routes/app/search'
import { Route as AppSeasonsRouteImport } from './routes/app/seasons'
import { Route as AppStatisticsRouteImport } from './routes/app/statistics'
import { Route as AppTorrentsRouteImport } from './routes/app/torrents'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SettingsAdvancedRouteImport } from './routes/settings/advanced'
import { Route as SettingsApplicationRouteImport } from './routes/settings/application'
import { Route as SettingsLibraryRouteImport } from './routes/settings/library'
import { Route as SettingsRecognitionRouteImport } from './routes/settings/recognition'
import { Route as SettingsServicesRouteImport } from './routes/settings/services'
import { Route as SettingsSharingRouteImport } from './routes/settings/sharing'
import { Route as SettingsTorrentsRouteImport } from './routes/settings/torrents'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SplashRoute = SplashRouteImport.update({
  id: '/splash',
  path: '/splash',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdateRoute = UpdateRouteImport.update({
  id: '/update',
  path: '/update',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAboutRoute = AppAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAnimeListRoute = AppAnimeListRouteImport.update({
  id: '/anime-list',
  path: '/anime-list',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppNowPlayingRoute = AppNowPlayingRouteImport.update({
  id: '/now-playing',
  path: '/now-playing',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSeasonsRoute = AppSeasonsRouteImport.update({
  id: '/seasons',
  path: '/seasons',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppStatisticsRoute = AppStatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTorrentsRoute = AppTorrentsRouteImport.update({
  id: '/torrents',
  path: '/torrents',
  getParentRoute: () => AppRouteRoute,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsAdvancedRoute = SettingsAdvancedRouteImport.update({
  id: '/advanced',
  path: '/advanced',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsApplicationRoute = SettingsApplicationRouteImport.update({
  id: '/application',
  path: '/application',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsLibraryRoute = SettingsLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsRecognitionRoute = SettingsRecognitionRouteImport.update({
  id: '/recognition',
  path: '/recognition',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsServicesRoute = SettingsServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsSharingRoute = SettingsSharingRouteImport.update({
  id: '/sharing',
  path: '/sharing',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsTorrentsRoute = SettingsTorrentsRouteImport.update({
  id: '/torrents',
  path: '/torrents',
  getParentRoute: () => SettingsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/settings': typeof SettingsRouteRouteWithChildren
  '/splash': typeof SplashRoute
  '/update': typeof UpdateRoute
  '/app/about': typeof AppAboutRoute
  '/app/anime-list': typeof AppAnimeListRoute
  '/app/history': typeof AppHistoryRoute
  '/app/now-playing': typeof AppNowPlayingRoute
  '/app/search': typeof AppSearchRoute
  '/app/seasons': typeof AppSeasonsRoute
  '/app/statistics': typeof AppStatisticsRoute
  '/app/torrents': typeof AppTorrentsRoute
  '/settings/advanced': typeof SettingsAdvancedRoute
  '/settings/application': typeof SettingsApplicationRoute
  '/settings/library': typeof SettingsLibraryRoute
  '/settings/recognition': typeof SettingsRecognitionRoute
  '/settings/services': typeof SettingsServicesRoute
  '/settings/sharing': typeof SettingsSharingRoute
  '/settings/torrents': typeof SettingsTorrentsRoute
  '/app/': typeof AppIndexRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/splash': typeof SplashRoute
  '/update': typeof UpdateRoute
  '/app/about': typeof AppAboutRoute
  '/app/anime-list': typeof AppAnimeListRoute
  '/app/history': typeof AppHistoryRoute
  '/app/now-playing': typeof AppNowPlayingRoute
  '/app/search': typeof AppSearchRoute
  '/app/seasons': typeof AppSeasonsRoute
  '/app/statistics': typeof AppStatisticsRoute
  '/app/torrents': typeof AppTorrentsRoute
  '/settings/advanced': typeof SettingsAdvancedRoute
  '/settings/application': typeof SettingsApplicationRoute
  '/settings/library': typeof SettingsLibraryRoute
  '/settings/recognition': typeof SettingsRecognitionRoute
  '/settings/services': typeof SettingsServicesRoute
  '/settings/sharing': typeof SettingsSharingRoute
  '/settings/torrents': typeof SettingsTorrentsRoute
  '/app': typeof AppIndexRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/settings': typeof SettingsRouteRouteWithChildren
  '/splash': typeof SplashRoute
  '/update': typeof UpdateRoute
  '/app/about': typeof AppAboutRoute
  '/app/anime-list': typeof AppAnimeListRoute
  '/app/history': typeof AppHistoryRoute
  '/app/now-playing': typeof AppNowPlayingRoute
  '/app/search': typeof AppSearchRoute
  '/app/seasons': typeof AppSeasonsRoute
  '/app/statistics': typeof AppStatisticsRoute
  '/app/torrents': typeof AppTorrentsRoute
  '/settings/advanced': typeof SettingsAdvancedRoute
  '/settings/application': typeof SettingsApplicationRoute
  '/settings/library': typeof SettingsLibraryRoute
  '/settings/recognition': typeof SettingsRecognitionRoute
  '/settings/services': typeof SettingsServicesRoute
  '/settings/sharing': typeof SettingsSharingRoute
  '/settings/torrents': typeof SettingsTorrentsRoute
  '/app/': typeof AppIndexRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/settings'
    | '/splash'
    | '/update'
    | '/app/about'
    | '/app/anime-list'
    | '/app/history'
    | '/app/now-playing'
    | '/app/search'
    | '/app/seasons'
    | '/app/statistics'
    | '/app/torrents'
    | '/settings/advanced'
    | '/settings/application'
    | '/settings/library'
    | '/settings/recognition'
    | '/settings/services'
    | '/settings/sharing'
    | '/settings/torrents'
    | '/app/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/splash'
    | '/update'
    | '/app/about'
    | '/app/anime-list'
    | '/app/history'
    | '/app/now-playing'
    | '/app/search'
    | '/app/seasons'
    | '/app/statistics'
    | '/app/torrents'
    | '/settings/advanced'
    | '/settings/application'
    | '/settings/library'
    | '/settings/recognition'
    | '/settings/services'
    | '/settings/sharing'
    | '/settings/torrents'
    | '/app'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/settings'
    | '/splash'
    | '/update'
    | '/app/about'
    | '/app/anime-list'
    | '/app/history'
    | '/app/now-playing'
    | '/app/search'
    | '/app/seasons'
    | '/app/statistics'
    | '/app/torrents'
    | '/settings/advanced'
    | '/settings/application'
    | '/settings/library'
    | '/settings/recognition'
    | '/settings/services'
    | '/settings/sharing'
    | '/settings/torrents'
    | '/app/'
    | '/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren
  SplashRoute: typeof SplashRoute
  UpdateRoute: typeof UpdateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/splash': {
      id: '/splash'
      path: '/splash'
      fullPath: '/splash'
      preLoaderRoute: typeof SplashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/update': {
      id: '/update'
      path: '/update'
      fullPath: '/update'
      preLoaderRoute: typeof UpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/about': {
      id: '/app/about'
      path: '/about'
      fullPath: '/app/about'
      preLoaderRoute: typeof AppAboutRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/anime-list': {
      id: '/app/anime-list'
      path: '/anime-list'
      fullPath: '/app/anime-list'
      preLoaderRoute: typeof AppAnimeListRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/history': {
      id: '/app/history'
      path: '/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/now-playing': {
      id: '/app/now-playing'
      path: '/now-playing'
      fullPath: '/app/now-playing'
      preLoaderRoute: typeof AppNowPlayingRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/search': {
      id: '/app/search'
      path: '/search'
      fullPath: '/app/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/seasons': {
      id: '/app/seasons'
      path: '/seasons'
      fullPath: '/app/seasons'
      preLoaderRoute: typeof AppSeasonsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/statistics': {
      id: '/app/statistics'
      path: '/statistics'
      fullPath: '/app/statistics'
      preLoaderRoute: typeof AppStatisticsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/torrents': {
      id: '/app/torrents'
      path: '/torrents'
      fullPath: '/app/torrents'
      preLoaderRoute: typeof AppTorrentsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/advanced': {
      id: '/settings/advanced'
      path: '/advanced'
      fullPath: '/settings/advanced'
      preLoaderRoute: typeof SettingsAdvancedRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/application': {
      id: '/settings/application'
      path: '/application'
      fullPath: '/settings/application'
      preLoaderRoute: typeof SettingsApplicationRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/library': {
      id: '/settings/library'
      path: '/library'
      fullPath: '/settings/library'
      preLoaderRoute: typeof SettingsLibraryRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/recognition': {
      id: '/settings/recognition'
      path: '/recognition'
      fullPath: '/settings/recognition'
      preLoaderRoute: typeof SettingsRecognitionRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/services': {
      id: '/settings/services'
      path: '/services'
      fullPath: '/settings/services'
      preLoaderRoute: typeof SettingsServicesRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/sharing': {
      id: '/settings/sharing'
      path: '/sharing'
      fullPath: '/settings/sharing'
      preLoaderRoute: typeof SettingsSharingRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/torrents': {
      id: '/settings/torrents'
      path: '/torrents'
      fullPath: '/settings/torrents'
      preLoaderRoute: typeof SettingsTorrentsRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppAboutRoute: typeof AppAboutRoute
  AppAnimeListRoute: typeof AppAnimeListRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppNowPlayingRoute: typeof AppNowPlayingRoute
  AppSearchRoute: typeof AppSearchRoute
  AppSeasonsRoute: typeof AppSeasonsRoute
  AppStatisticsRoute: typeof AppStatisticsRoute
  AppTorrentsRoute: typeof AppTorrentsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAboutRoute: AppAboutRoute,
  AppAnimeListRoute: AppAnimeListRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppNowPlayingRoute: AppNowPlayingRoute,
  AppSearchRoute: AppSearchRoute,
  AppSeasonsRoute: AppSeasonsRoute,
  AppStatisticsRoute: AppStatisticsRoute,
  AppTorrentsRoute: AppTorrentsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface SettingsRouteRouteChildren {
  SettingsAdvancedRoute: typeof SettingsAdvancedRoute
  SettingsApplicationRoute: typeof SettingsApplicationRoute
  SettingsLibraryRoute: typeof SettingsLibraryRoute
  SettingsRecognitionRoute: typeof SettingsRecognitionRoute
  SettingsServicesRoute: typeof SettingsServicesRoute
  SettingsSharingRoute: typeof SettingsSharingRoute
  SettingsTorrentsRoute: typeof SettingsTorrentsRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsAdvancedRoute: SettingsAdvancedRoute,
  SettingsApplicationRoute: SettingsApplicationRoute,
  SettingsLibraryRoute: SettingsLibraryRoute,
  SettingsRecognitionRoute: SettingsRecognitionRoute,
  SettingsServicesRoute: SettingsServicesRoute,
  SettingsSharingRoute: SettingsSharingRoute,
  SettingsTorrentsRoute: SettingsTorrentsRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
  SplashRoute: SplashRoute,
  UpdateRoute: UpdateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
