import { AppWindowIcon, DownloadIcon, FolderIcon, GlobeIcon, ScanEyeIcon, Share2Icon, SlidersHorizontalIcon } from "lucide-react";

export const settingsSections = [
	{ id: "services", label: "Services", description: "List providers and account login.", icon: GlobeIcon },
	{ id: "library", label: "Library", description: "Folders Biyori scans for episodes.", icon: FolderIcon },
	{ id: "application", label: "Application", description: "Titles, startup, updates, and tray.", icon: AppWindowIcon },
	{ id: "recognition", label: "Recognition", description: "Match playing media to your list.", icon: ScanEyeIcon },
	{ id: "sharing", label: "Sharing", description: "Discord presence and local HTTP.", icon: Share2Icon },
	{ id: "torrents", label: "Torrents", description: "Feeds, downloads, and filters.", icon: DownloadIcon },
	{ id: "advanced", label: "Advanced", description: "Low-level options. Change with care.", icon: SlidersHorizontalIcon },
] as const;

export type SettingsSectionId = (typeof settingsSections)[number]["id"];

export const settingsFieldSection: Record<string, SettingsSectionId> = {
	defaultService: "services",
	titleLanguage: "application",
	defaultAddToListStatus: "application",
	autostart: "application",
	autostartTray: "application",
	updateChannel: "application",
	closeToTray: "application",
	externalLinks: "application",
	libraryFolders: "library",
	realtimeMonitor: "library",
	ignoreOutsideLibrary: "recognition",
	ignoreOutOfRangeEpisode: "recognition",
	recognitionDelaySeconds: "recognition",
	askToConfirmUpdate: "recognition",
	enableRecognition: "recognition",
	enableMediaPlayerDetection: "recognition",
	enableStreamingDetection: "recognition",
	enabledMediaPlayers: "recognition",
	enabledStreamingProviders: "recognition",
	notifyOnRecognized: "recognition",
	notifyOnUnrecognized: "recognition",
	goToNowPlayingOnRecognized: "recognition",
	goToNowPlayingOnUnrecognized: "recognition",
	playerMustBeInFocus: "recognition",
	rssFeedUrl: "torrents",
	rssSearchUrl: "torrents",
	checkTorrentsAutomatically: "torrents",
	torrentCheckIntervalMinutes: "torrents",
	newTorrentAction: "torrents",
	torrentFilterEnabled: "torrents",
	torrentFilters: "torrents",
	torrentAppMode: "torrents",
	torrentAppOpen: "torrents",
	torrentAppPath: "torrents",
	torrentUseAnimeFolder: "torrents",
	torrentFallbackOnFolder: "torrents",
	torrentCreateSubfolder: "torrents",
	torrentDownloadDir: "torrents",
	torrentFileDownloadPath: "advanced",
	torrentUseMagnet: "advanced",
	torrentDownloadSortBy: "torrents",
	torrentDownloadSortOrder: "torrents",
	torrentArchiveMaxCount: "advanced",
	ignoredStrings: "recognition",
	waitUntilPlayerExits: "recognition",
	updateRichPresence: "sharing",
	showElapsedTime: "sharing",
	enableHttp: "sharing",
	httpPort: "sharing",
	discordApplicationId: "sharing",
	uiTheme: "advanced",
	fileSizeThreshold: "advanced",
	mediaDetectionInterval: "advanced",
};
