# This is a basic workflow to help you get started with Actions

name: Upload Release

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: 
  release:
    types: [prereleased, released]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2
        with:
          # Destination path
          path: ./release/
      - name: upload release
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./release/
          asset_name: release-${{ github.event.release.tag_name }}.zip
          asset_content_type: application/zip
